export const requaredField = 'Это обязательное поле'
export const emailIsNotCorrect = 'Некорректный email'
export const minLengthIsSix = 'Минимальная длинна 6 символов'
export const minLengthIsTwo = 'Минимальная длинна 2 символов'
export const passwordDoNotMatch = 'Пароли не совпадают'
